### ISSUE TITLE
Errors after upgrade

### ISSUE THREAD

**Issue by srentfrow** [DNNCommunity/DNN.Documents#18]
I upgraded my DNN Documents module from v6.2.5 to v7.0.0 then upgraded DNN from v9.1.1 to v9.2.2. I got no errors during any of the installs but when I tried to add a new document to make sure the module still worked as expected I got the followed error:

![image](https://user-images.githubusercontent.com/96082804/145877822-e4c2f87c-90d3-41d6-a971-a6dcbdb6ae4a.png)

and then the following is added to my log files:

```
2021-12-13 09:47:08,124 [SERVERREPLACED][Thread:5][ERROR] DotNetNuke.Services.Exceptions.Exceptions - FriendlyMessage="Error:  is currently unavailable." ctrl="ASP.desktopmodules_documents_editdocs_ascx" exc="System.ArgumentException: Item has already been added. Key in dictionary: ''  Key being added: ''
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at DotNetNuke.Modules.Documents.EditDocs.CheckRolesMatch(ModulePermissionCollection ModuleRoles, FolderPermissionCollection FileRoles)
   at DotNetNuke.Modules.Documents.EditDocs.CheckFileSecurity(String Url)
   at DotNetNuke.Modules.Documents.EditDocs.Update(Boolean Override)"
2021-12-13 09:47:09,311 [SERVERREPLACED][Thread:6][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.Exception: Job #185be6d7-1401-434b-97f1-c998e7c51bf7 (Item dnnfile-6693 from portal 0) is skipped and will be removed from queue. Job details: {"Guid":"185be6d7-1401-434b-97f1-c998e7c51bf7","Priority":5,"Due":"2021-12-13T14:47:03.233+00:00","Action":"add","BehaviorId":4,"PortalId":0,"TabId":-1,"ModuleId":-1,"ItemId":"dnnfile-6693","Contents":null,"ContentType":"application/pdf","Metadata":{"PortalId":0,"ItemId":null,"Title":"","LockTitle":false,"OriginalId":null,"OriginalName":null,"OriginalPath":null,"AuthorId":0,"AuthorName":null,"TitleToken":"","Description":"","LockDescription":false,"Keywords":"","Boost":null,"OverrideUrl":null,"Source":null,"LinkToTabId":null,"Categories":[],"UrlHash":null,"Data":[],"Locale":null,"IgnoreSecurity":null,"FileTime":"0001-01-01T00:00:00","Roles":[],"DeniedRoles":[],"AllowedUsers":[],"DeniedUsers":[],"Type":null,"SubType":null,"ContainerPath":null,"ItemPath":null,"Url":null,"DatePublished":"0001-01-01T00:00:00+00:00","QueryString":null,"ContainerId":null,"ContainerName":null},"ContentSourceId":"DnnFiles","ContentClient":"DnnFile","ContentClientOptions":null,"ContentParser":"","ContentParserOptions":null,"DatePublished":"2021-12-13T14:47:03.233+00:00","Status":"Skip","RetryCount":0,"IsDeleted":false}
```

The error seems to speak to roles and permissions. I am currently signed in as a superuser and I checked that the selected folder does have the correct permissions so I’m a bit stumped. Any help would be appreciated.

I also tried updating the Documents module again from v7.0 to v7.1 and I have the same errors.

**Comment by mitchelsellers** [comment]
I believe this is an older issue, if you can still recreate please feel free to reopen.
