### ISSUE TITLE
Issue installing module on DNN 9 instance

### ISSUE THREAD

**Issue by rdh755** [DNNCommunity/DNN.Documents#3]
**Describe the bug**
When installing extension on DNN 9 instance, I receive the following SQL error:

Failure SQL Execution resulted in following Exceptions: 
 System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'DefaultFolder'.
 Incorrect syntax near 'AllowUserSort'.
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:a0f90f14-cb15-41b2-a77e-6507bb21de9e
 Error Number:102,State:1,Class:15
 
 --Discrepancy fix for upgrades prior to version 06.00.00
 IF (SELECT COLUMNPROPERTY( OBJECT_ID('dbo.DocumentsSettings'),'AllowUserSort','AllowsNull')) IS NULL 
 ALTER TABLE dbo.DocumentsSettings 
 DefaultFolder NVARCHAR(2000) NULL,
 CategoriesListName NVARCHAR(50) NULL,
 ADD AllowUserSort BIT NULL

**To Reproduce**
1. Go to instance for DNN 9
2. Click on Settings -> Extensions
3. Install DNN.Documents 7.0

**Expected behavior**
Module should install to DNN instance.

**Screenshots**

**DNN Information (please complete the following information):**
* DNN Version 9
* Documents Module Version 7.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome, IE

**Additional context**
Compiled and built the package to install. Upgrading module from 5.0 to 7.0. Seems like 6.0 sql exception is preventing installation on DNN 9.

**Comment by rdh755** [comment]
Found the issue. Apparently, the ALTER TABLE script part was written incorrectly, which caused the prevention of installation. It should go like this:

```
--Discrepancy fix for upgrades prior to version 06.00.00
IF (SELECT COLUMNPROPERTY( OBJECT_ID('{databaseOwner}{objectQualifier}DocumentsSettings'),'AllowUserSort','AllowsNull')) IS NULL 
	ALTER TABLE {databaseOwner}{objectQualifier}DocumentsSettings
		ADD DefaultFolder NVARCHAR(2000) NULL,
		CategoriesListName NVARCHAR(50) NULL,
		AllowUserSort BIT NULL
GO
```

**Comment by rdh755** [comment]
@mitchelsellers
I don't have permissions to edit any SQL scripts for this module, but I figure I should let you know about this.

**Comment by valadas** [comment]
Should be fixed with the latest release here https://github.com/DNNCommunity/DNN.Documents/releases/tag/07.01.00
